# Generated by Django 3.1.5 on 2023-05-10 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=256)),
                ('patient_birth_date', models.DateField(help_text='Patient birth date')),
                ('patient_med_condition', models.TextField()),
                ('doctor', models.ManyToManyField(related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
