# Generated by Django 3.1.5 on 2023-05-11 07:48

from django.db import migrations, models
import django.db.models.deletion
import main.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main.helpers.UploadTo('patients'))),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to='main.patienthistory')),
            ],
        ),
    ]
